config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'welcome#index'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :doctors, skip: [:registrations], controllers: { sessions: 'doctors/sessions' }
  get '/doctors', to: 'doctors#index'

  devise_for :patients, controllers: { registrations: 'patients/registrations', sessions: 'patients/sessions' }

  resources :appointments

  resource :profile, only: %i[show update], controller: 'profile' do
    post :update_password
    post :update_photo
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include ApplicationHelper

  validates :name, length: { minimum: 2 }
  validates :surname, length: { minimum: 2 }
  validates :residence, length: { minimum: 8, maximum: 30 }
  validates :password, allow_blank: true, length: { minimum: 6 }
  validates :password_confirmation, allow_blank: true, length: { minimum: 6 }
  validates :age, numericality: { less_than_or_equal_to: 100, only_integer: true }
  validates :phone, format: { with: self::FORMAT_NUMBER_PHONE, message: I18n.t('models.validates_phone'),
                              uniqueness: true }

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/patients/registrations_controller.rb
# frozen_string_literal: true

class Patients::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def edit
    super
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :phone, :age, :gender, :residence])
  end
end

app/controllers/patients/sessions_controller.rb
# frozen_string_literal: true

class Patients::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  rescue
    flash[:notice] = "Error: Incorrect password or phone number!"
    redirect_to new_patient_session_path
  end
end

app/controllers/patients/unlocks_controller.rb
# frozen_string_literal: true

class Patients::UnlocksController < Devise::UnlocksController
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('patient.links.new_session'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('patient.links.new_registration'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('patient.links.new_doctor_session'), new_doctor_session_path %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('patient.links.new_confirmation'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('patient.links.new_unlock'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>