config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'welcome#index'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :doctors, skip: [:registrations], controllers: { sessions: 'doctors/sessions' }
  get '/doctors', to: 'doctors#index'

  devise_for :patients, controllers: { registrations: 'patients/registrations', sessions: 'patients/sessions' }

  resources :appointments

  resource :profile, only: %i[show update], controller: 'profile' do
    post :update_password
    post :update_photo
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include ApplicationHelper

  validates :name, length: { minimum: 2 }
  validates :surname, length: { minimum: 2 }
  validates :residence, length: { minimum: 8, maximum: 30 }
  validates :password, allow_blank: true, length: { minimum: 6 }
  validates :password_confirmation, allow_blank: true, length: { minimum: 6 }
  validates :age, numericality: { less_than_or_equal_to: 100, only_integer: true }
  validates :phone, format: { with: self::FORMAT_NUMBER_PHONE, message: I18n.t('models.validates_phone'),
                              uniqueness: true }

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/patients/registrations_controller.rb
# frozen_string_literal: true

class Patients::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def edit
    super
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :phone, :age, :gender, :residence])
  end
end

app/controllers/patients/sessions_controller.rb
# frozen_string_literal: true

class Patients::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  rescue
    flash[:notice] = "Error: Incorrect password or phone number!"
    redirect_to new_patient_session_path
  end
end

app/controllers/patients/unlocks_controller.rb
# frozen_string_literal: true

class Patients::UnlocksController < Devise::UnlocksController
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/profile.html.erb
<div style="margin-left: 1%">
  <h1>Patient info:</h1>
  <ul>
    <li>Name: <%= current_patient.name %></li>
    <li>Surname: <%= current_patient.surname %></li>
    <li>Age: <%= current_patient.age %></li>
    <li>Phone: <%= current_patient.phone %></li>
    <li>Gender: <%= current_patient.gender %></li>
    <li>Residence: <%= current_patient.residence %></li>
  </ul>
  <h2>Change password:</h2>
  <%= link_to "Change your password", edit_patient_registration_path %>
  <h2>Change data patient:</h2>
  <%= form_with url: "/update/patient/#{current_patient.id}", method: :post do |f| %>
    <div class="field">
      <%= f.label :phone %><br />
      <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone", placeholder: "+380*********", value: current_patient.phone %>
    </div>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", value: current_patient.name %>
    </div>

    <div class="field">
      <%= f.label :surname %><br />
      <%= f.text_field :surname, autofocus: true, autocomplete: "surname", value: current_patient.surname %>
    </div>

    <div class="field">
      <%= f.label :age %><br />
      <%= f.number_field :age, autofocus: true, autocomplete: "age", value: current_patient.age %>
    </div>

    <div class="field">
      <%= f.label :gender %><br />
      <%= radio_button_tag(:gender, "man") %>
        <%= label_tag(:gender_man, "I'm a man") %>
      <%= radio_button_tag(:gender, "women") %>
        <%= label_tag(:gender_women, "I'm a women") %>
    </div>

    <div class="field">
      <%= f.label :residence %><br />
      <%= f.text_field :residence, autofocus: true, autocomplete: "residence", value: current_patient.residence %>
    </div>

    <div style="margin-top: .5%">
      <%= f.submit "Update" %>
    </div>
  <% end %>
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
</div>