config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'welcome#index'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :doctors, skip: [:registrations], controllers: { sessions: 'doctors/sessions' }
  get '/doctors', to: 'doctors#index'

  devise_for :patients, controllers: { registrations: 'patients/registrations', sessions: 'patients/sessions' }

  resources :appointments

  resource :profile, only: %i[show update], controller: 'profile' do
    post :update_password
    post :update_photo
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :recommendation, allow_blank: true, length: { minimum: 5 }

  paginates_per 15
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  check_authorization unless: :devise_controller?
  load_and_authorize_resource

  def index
    @appointments = AppointmentsListQuery.new(current_user, index_params).list
  end

  def show; end

  def new
    @appointment = Appointment.new
    @doctors = Doctor.all
  end

  def edit; end

  def create
    creating = AppointmentCreatorService.new(appointment_params).create_appointment

    if creating.success?
      redirect_to appointments_path, notice: creating.notice
    else
      redirect_to appointments_path, status: :unprocessable_entity,
                                     notice: creating.notice
    end
  end

  def update
    updating = AppointmentRecommendationUpdaterService.new(appointment, params[:recommendation]).add_recommendation

    if updating.success?
      redirect_to appointment_url(appointment), notice: updating.notice
    else
      render :edit, status: :unprocessable_entity, locals: { appointment: appointment }, notice: updating.notice
    end
  end

  def destroy
    appointment.destroy!
    redirect_to appointments_url, notice: I18n.t('controllers.appointments.successful_destroy')
  end

  private

  def index_params
    params.permit(:status, :page, :date)
  end

  def appointment
    @appointment ||= Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :status, :recommendation, :date)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Doctor:</strong>
    <%= "#{appointment.doctor.surname} #{appointment.doctor.name} #{appointment.doctor.category.title}" %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= "#{appointment.patient.surname} #{appointment.patient.name}" %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= appointment.date %>
  </p>

  <p>
    <strong>Recommendation:</strong>
    <%= appointment.recommendation %>
  </p>

</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% all_doctors = @doctors.map { |doctor|
                                  unless doctor.category_id.nil?
                                    ["#{doctor.surname} #{doctor.name} #{doctor.category.title}", doctor.id]
                                  else
                                    nil
                                  end
                                } %>
    <%= form.label :doctor_id, style: "display: block" %>
    <%= form.select :doctor_id, all_doctors %>
  </div>

  <div>
     <%= form.hidden_field :patient_id, :value => current_patient.id %>
  </div>

  <div>
     <%= form.hidden_field :status, :value => "wait" %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_select :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<% flash.each do |type, msg| %>
  <div class="alert alert-danger">
    <%= msg %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div style="margin-left: 1%">
  <h1>Add recommendation appointment</h1>
  <%= form_for @appointment, method: :patch do |form| %>
    <% invalid = @appointment.errors.include?(:recommendation) %>
    <div class="form-group w-25 p-3">
      <%= form.label :recommendation %>
      <%= form.text_area :recommendation, class: "form-control #{'is-invalid' if invalid}" %>
      <% if invalid %>
        <div class="invalid-feedback d-block">
          <% @appointment.errors.full_messages_for(:recommendation).each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div>

    <div>
      <%= form.submit "Add recommendation" %>
    </div>
  <% end %>

  <br>

  <div>
    <%= link_to "Show this appointment", @appointment %> |
    <%= link_to "Back to appointments", appointments_path %>
  </div>
</div>

app/views/appointments/index.html.erb
<div style="margin-left: 1%">
  <p style="color: green"><%= notice %></p>
  <h3><%= t('appointment.index.search') %></h3>
  <%= form_with url: "/appointments/", method: :get do |f| %>
    <%= f.label :search_date, style: "display: block" %>
    <%= f.date_field :date %>
    <br>
    <%= f.label :status, style: "display: block" %>
    <%= radio_button_tag(:status, "wait") %>
      <%= label_tag(:status_wait, "Wait status") %>
    <%= radio_button_tag(:status, "done") %>
      <%= label_tag(:status_done, "Done status") %>
    <br>
    <%= submit_tag t('appointment.index.search') %>
  <% end %>
  <% if can? :create, Appointment %>
    <%= link_to t('appointment.index.new_appointment'), new_appointment_path %>
  <% end %>
  <% if patient_signed_in? %>
    <h1><%= t('appointment.index.patient_appointments') %></h1>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col"><%= t('appointment.index.photo') %></th>
          <th scope="col"><%= t('appointment.index.doctor') %></th>
          <th scope="col"><%= t('appointment.index.status') %></th>
          <th scope="col"><%= t('appointment.index.date') %></th>
          <th scope="col"><%= t('appointment.index.deteils') %></th>
        </tr>
        </thead>
        <tbody>
          <% @appointments.each do |appointment| %>
              <tr>
                <td>#</td>
                <td>
                  <%= "#{appointment.doctor.surname} #{appointment.doctor.name} - #{appointment.doctor.category.title}" %>
                </td>
                <td><%= appointment.status %></td>
                <td><%= appointment.date %></td>
                <td><%= link_to t('appointment.index.show_appointment'), appointment %></td>
              </tr>
          <% end %>
        </tbody>
    </table>
  <% elsif doctor_signed_in? %>
    <h1><%= t('appointment.index.doctor_appointments') %></h1>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col"><%= t('appointment.index.patient') %></th>
          <th scope="col"><%= t('appointment.index.status') %></th>
          <th scope="col"><%= t('appointment.index.date') %></th>
          <th scope="col"><%= t('appointment.index.deteils') %></th>
        </tr>
        </thead>
        <tbody>
          <% @appointments.each do |appointment| %>
            <% if appointment.doctor_id.eql? current_doctor.id %>
              <tr>
                <td>
                  <%= "#{appointment.patient.surname} #{appointment.patient.name} #{appointment.patient.phone}" %>
                </td>
                <td><%= appointment.status %></td>
                <td><%= appointment.date %></td>
                <td><%= link_to t('appointment.index.show_appointment'), appointment %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
    </table>
  <% else %>
    <h1><%= t('appointment.index.not_authorized') %></h1>
  <% end %>
  <%= paginate @appointments %>
</div>

app/views/appointments/new.html.erb
<div style="margin-left: 1%">
  <h1>New appointment</h1>

  <%= render "form", appointment: @appointment %>

  <br>

  <div>
    <%= link_to "Back to appointments", appointments_path %>
  </div>
</div>

app/views/appointments/show.html.erb
<div style="margin-left: 1%">
  <p style="color: green"><%= notice %></p>

  <%= render @appointment %>

  <div>
    <% if can? :update, @appointment %>
      <%= link_to "Add recommendation", edit_appointment_path(@appointment) %> |
    <% end %>
    <%= link_to "Back to appointments", appointments_path %>

    <%= button_to "Destroy this appointment", @appointment, method: :delete %>
  </div>
</div>