config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'welcome#index'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :doctors, skip: [:registrations], controllers: { sessions: 'doctors/sessions' }
  get '/doctors', to: 'doctors#index'

  devise_for :patients, controllers: { registrations: 'patients/registrations', sessions: 'patients/sessions' }

  resources :appointments

  resource :profile, only: %i[show update], controller: 'profile' do
    post :update_password
    post :update_photo
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Doctor, public: true

    if user.instance_of?(::AdminUser)
      can :manage, :all
    elsif user.instance_of?(::Doctor)
      can :manage, Appointment, doctor: user
      cannot :create, Appointment
      can :manage, Doctor, id: user.id
      can :manage, Profile
    elsif user.instance_of?(::Patient)
      can :manage, Appointment, patient: user
      cannot :update, Appointment
      can :manage, Patient, id: user.id
      can :manage, Profile
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :recommendation, allow_blank: true, length: { minimum: 5 }

  paginates_per 15
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctors, dependent: :nullify

  validates :title, uniqueness: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :category, optional: true
  has_many :appointments
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include ApplicationHelper

  validates :name, length: { minimum: 2 }
  validates :surname, length: { minimum: 2 }
  validates :encrypted_password, allow_blank: true, length: { minimum: 6 }
  validates :password, allow_blank: true, length: { minimum: 6 }
  validates :password_confirmation, allow_blank: true, length: { minimum: 6 }
  validates :phone, format: { with: self::FORMAT_NUMBER_PHONE, message: I18n.t('models.validates_phone'),
                              uniqueness: true }

  paginates_per 5

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include ApplicationHelper

  validates :name, length: { minimum: 2 }
  validates :surname, length: { minimum: 2 }
  validates :residence, length: { minimum: 8, maximum: 30 }
  validates :password, allow_blank: true, length: { minimum: 6 }
  validates :password_confirmation, allow_blank: true, length: { minimum: 6 }
  validates :age, numericality: { less_than_or_equal_to: 100, only_integer: true }
  validates :phone, format: { with: self::FORMAT_NUMBER_PHONE, message: I18n.t('models.validates_phone'),
                              uniqueness: true }

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < ActiveAdmin::Devise::SessionsController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery
  before_action :set_locale

  def configure_permitted_parameters
    update_attrs = %i[password password_confirmation current_password]
    devise_parameter_sanitizer.permit :account_update, keys: update_attrs
  end

  private

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

  def current_user
    @current_user ||=
      if patient_signed_in?
        current_patient
      elsif doctor_signed_in?
        current_doctor
      elsif admin_user_signed_in?
        current_admin_user
      end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  check_authorization unless: :devise_controller?
  load_and_authorize_resource

  def index
    @appointments = AppointmentsListQuery.new(current_user, index_params).list
  end

  def show; end

  def new
    @appointment = Appointment.new
    @doctors = Doctor.all
  end

  def edit; end

  def create
    creating = AppointmentCreatorService.new(appointment_params).create_appointment

    if creating.success?
      redirect_to appointments_path, notice: creating.notice
    else
      redirect_to appointments_path, status: :unprocessable_entity,
                                     notice: creating.notice
    end
  end

  def update
    updating = AppointmentRecommendationUpdaterService.new(appointment, params[:recommendation]).add_recommendation

    if updating.success?
      redirect_to appointment_url(appointment), notice: updating.notice
    else
      render :edit, status: :unprocessable_entity, locals: { appointment: appointment }, notice: updating.notice
    end
  end

  def destroy
    appointment.destroy!
    redirect_to appointments_url, notice: I18n.t('controllers.appointments.successful_destroy')
  end

  private

  def index_params
    params.permit(:status, :page, :date)
  end

  def appointment
    @appointment ||= Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :status, :recommendation, :date)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = DoctorsListQuery.new(index_params).list
  end

  private

  def index_params
    params.permit(:category, :surname, :page)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  check_authorization unless: :devise_controller?
  load_and_authorize_resource

  def show; end

  def update
    @updating = ProfileUpdaterService.new(current_user, update_params).update

    update_notice
  end

  def update_photo
    @updating = ProfilePhotoUpdaterService.new(current_user, params[:avatar]).update_photo

    update_notice
  end

  def update_password
    updating = ProfilePasswordUpdaterService.new(current_user, update_password_params).update_password

    if updating.success?
      redirect_to new_patient_session_path, notice: updating.notice
    else
      redirect_to profile_path, status: :unprocessable_entity, notice: updating.notice
    end
  end

  def update_notice
    if @updating.success?
      redirect_to profile_path, notice: @updating.notice
    else
      redirect_to profile_path, status: :unprocessable_entity, notice: @updating.notice
    end
  end

  private

  def update_password_params
    params.permit(:password, :password_confirmation)
  end

  def update_params
    params.permit(:name, :surname, :phone, :age, :gender, :residence, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  FORMAT_NUMBER_PHONE = /\A\+?380[345679]\d{8}\z/
  
  def doctor_avatar(doctor, size=40)
    if doctor.avatar.attached?
      doctor.avatar.key
    else
      "149071_qgovwv"
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/_flash_message.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('header.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/"><%= t('header.title') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if patient_signed_in? %>
            <%= link_to t('header.profile'), profile_path(current_patient), class: "nav-item nav-link active" %>
            <%= link_to t('header.doctors'), doctors_path, class: "nav-item nav-link active" %>
            <%= link_to t('header.appointments_patient'), appointments_path, class: "nav-item nav-link active" %>
            <%= link_to t('header.log_out'), destroy_patient_session_path, method: :delete, class: "nav-item nav-link active" %>
          <% elsif doctor_signed_in? %>
            <%= link_to t('header.profile'), profile_path(current_doctor), class: "nav-item nav-link active" %>
            <%= link_to t('header.appointments_doctor'), appointments_path, class: "nav-item nav-link active" %>
            <%= link_to t('header.log_out'), destroy_doctor_session_path, method: :delete, class: "nav-item nav-link active" %>
          <% else %>
            <%= link_to t('header.doctors'), doctors_path, class: "nav-item nav-link active" %>
            <%= link_to t('header.log_in'), new_patient_session_path, class: "nav-item nav-link active" %>
          <% end %>
        </div>
      </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>